FROM ghcr.io/christopher-tiangco/the-mashmake-blog:latest
COPY the-mashmake-blog/ /home/the-mashmake-blog/
WORKDIR /home/the-mashmake-blog
RUN bundle install
RUN rails db:migrate
CMD rails s -b 0.0.0.0 -p 3030
