name: CI-CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-push-to-registry:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
          
      - name: Setup QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      # Build for multiple platforms
      - name: Build app to run on multiple platforms
        run: |
          docker buildx create --name mybuilder --use
          docker buildx inspect --bootstrap
          docker buildx build -f ci/Dockerfile --push --platform linux/arm/v7,linux/amd64  -t ghcr.io/${{ github.actor }}/the-mashmake-blog:latest
          docker push ghcr.io/${{ github.actor }}/the-mashmake-blog:latest
